# ======================================================================================================================


# Code formatting

[tool.autoflake]
remove_all_unused_imports = true   # Remove all unused imports
ignore_init_module_imports = true  # Ignore unused imports in `__init__.py` files
in_place = true                    # Modify files directly instead of printing changes to the console
recursive = true                   # Recursively check directories

[tool.black]
line-length = 120                  # Maximum line length

[tool.isort]
force_grid_wrap = 2                # Disable automatic row wrapping
include_trailing_comma = true      # Add a comma after the last element in parentheses
line_length = 120                  # Maximum line length (recommended for black compatibility)
lines_after_imports = 2            # Number of blank lines to leave after imports
multi_line_output = 3              # Use import format with hyphens in parentheses

# ======================================================================================================================


# Linting

[tool.mypy]
ignore_missing_imports = true  # Ignore missing type annotations for external libraries
strict = true                  # Strict mode for type checking
explicit_package_bases = true  # Avoid confusion between local and installed packages

# ======================================================================================================================